# Generated by Django 4.1.5 on 2023-01-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmratingweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
