# Generated by Django 4.1.5 on 2023-02-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmratingweb', '0003_movie_description_movie_imdb_rating_movie_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('species', models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='additional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmratingweb.additional_inf'),
        ),
    ]
