# Generated by Django 4.1.5 on 2023-02-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmratingweb', '0005_alter_additional_inf_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_inf',
            name='species',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Musical'), (5, 'Komedia rom.'), (1, 'Dramat historyczny'), (3, 'Familijny'), (0, 'Inne'), (2, 'Komedia')], default=0),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(default=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmratingweb.movie')),
            ],
        ),
    ]
