# Generated by Django 4.1.5 on 2023-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmratingweb', '0006_alter_additional_inf_species_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_inf',
            name='species',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (4, 'Musical'), (5, 'Komedia rom.'), (0, 'Inne'), (3, 'Familijny'), (1, 'Dramat historyczny')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('movie', models.ManyToManyField(related_name='aktorzy', to='filmratingweb.movie')),
            ],
        ),
    ]
